apiVersion: v1
kind: Pod
metadata:
  name: demo-01-basic-pod
  namespace: demo-01
  labels:
    awesome: definitely
  annotations:
    description: this is my super awesome pod that does all sorts of cool things
spec:
  containers:
  - name: nginx
    image: nginx:1.21.3
    env:
    - name: FOO
      value: bar
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 200m
        memory: 200Mi
    livenessProbe:
      httpGet:
        path: /health
        port: 80
