apiVersion: v1
kind: Pod
metadata:
  name: demo-01-failing-pod
  namespace: demo-01
spec:
  containers:
  - args:
      - /bin/sh
      - -c
      - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600
    image: busybox
    livenessProbe:
      exec:
        command:
          - cat
          - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
    name: failing-pod


