apiVersion: v1
kind: Pod
metadata:
  name: demo-01-volume-pod
  namespace: demo-01
spec:
  containers:
    - command:
        - /bin/sh
        - -c
        - touch /volumes/container-a/hi-from-a; sleep "3600"
      image: busybox
      name: a
      volumeMounts:
        - mountPath: /volumes/container-a
          name: my-shared-volume
    - command:
        - /bin/sh
        - -c
        - touch /volumes/container-b/hi-from-b; sleep "3600"
      image: busybox
      name: b
      volumeMounts:
        - mountPath: /volumes/container-b
          name: my-shared-volume
  volumes:
    - name: my-shared-volume
      emptyDir: {}
